---
server:
  port: 8010
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
---
spring:
  profiles: primary
server:
  port: 8011
  
---
spring:
  profiles: secondary
server:
  port: 8012
  
---
spring:
  profiles: tertiary
server:
  port: 8013