words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 8084